### ISSUE TITLE
panic: index out of range [0] with length 0

### ISSUE THREAD

**Issue by pmphry** [silkeh/ipcipher#1]
Hi, I'm interested in using ipcipher as a means for encrypting IP addresses in order to sanitize PCAP samples.  However, in using the master branch, I'm encountering a panic even running the simplest examples.  For instance, the example from the readme:

```
package main

import (
	"fmt"
	"net"

	"github.com/silkeh/ipcipher"
)

func main() {
	key := ipcipher.GenerateKeyFromPassword("ipcipher")
	src := net.ParseIP("127.0.0.1")
	dst := net.IPv6unspecified
	ipcipher.Encrypt(key, dst, src)
	fmt.Printf("%s encrypted to %s\n", src, dst)
}
```

results in a panic and runtime error:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/silkeh/ipcipher.xor4(...)
	/Users/adam/go/pkg/mod/github.com/silkeh/ipcipher@v0.0.0-20200803185944-84d8eb63eeaa/ipcrypt.go:65
github.com/silkeh/ipcipher.EncryptIPv4(0xc00001c2c0, 0x0, 0x0, 0x0, 0xc00001c2fc, 0x4, 0x4)
	/Users/adam/go/pkg/mod/github.com/silkeh/ipcipher@v0.0.0-20200803185944-84d8eb63eeaa/ipcrypt.go:75 +0x23d
github.com/silkeh/ipcipher.Encrypt(0xc00001c2c0, 0x11b5140, 0x10, 0x10, 0xc00001c2f0, 0x10, 0x10, 0x300000002, 0xc000000180)
	/Users/adam/go/pkg/mod/github.com/silkeh/ipcipher@v0.0.0-20200803185944-84d8eb63eeaa/ipcipher.go:53 +0xc5
main.main()
	/Users/adam/go/src/pcap-dev/main.go:14 +0xdc
```

The behavior has been the same on go1.14 and go1.16.   Am I missing something?   I'm new to debugging Go packages, but I have tried adjusting how I initialize Encrypt() arguments to no avail.  Any advise would be much appreciated.

**Comment by silkeh** [comment]
Thanks for reporting! Looks like the example was incorrect (`net.IPv6unspecified` should be `net.IPv4zero`).

I have added [testable examples](https://pkg.go.dev/github.com/silkeh/ipcipher#example-Encrypt) and removed the examples from the README.
